### ISSUE TITLE
Typos in CMakeLists.txt

### ISSUE THREAD

**Issue by drumaddict** [bsamseth/cpp-project#2]
In `CMakeLists.txt` file, line 12 should be
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -g")`
instead of 
`set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -Wall -g")`,
I found this out after I tried  to debug `main.cpp` ,
 breakpoints could not be set because flag -g was not set.

Same with line 17, should be
`set(CMAKE_CXX_FLAGS "-Wall -O2")`

Also, after you pull googletest, all paths to googletest need one more segment googletest, 
For example
`{PROJECT_SOURCE_DIR}/external/googletest`
should become
`{PROJECT_SOURCE_DIR}/external/googletest/googletest`
and so on.
Great boilerplate repo, very useful.

**Comment by bsamseth** [comment]
@drumaddict Thank you for this, fun to see that others found a use for this!

A made a fix for the simple typo. I'm not sure what you mean with the issue regarding googletest. It seems to work fine the way its set up. What is the problem, exactly?

I'll merge the fix once it can resolve this issue completely.

**Comment by drumaddict** [comment]
I pulled googletest and it was put in  `external\googletest\googletest`,
so all paths in `CMakeLists.txt` need one more `googletest` segment.
I could't compile the test file without this change.
See attached image from vim, see the location of googletest.
Could it be that I did something wrong? I just did `git submodule update`.
![googletest](https://cloud.githubusercontent.com/assets/323951/25440463/3826720a-2aa8-11e7-89e1-bd44f6ecb0cc.png)

**Comment by bsamseth** [comment]
Did you pull googletest yourself? Cmake is set up to do this for you. On a clean clone I did the following, which worked fine:

    mkdir build && cd build && cmake .. && make && ./unit_tests.x

**Comment by drumaddict** [comment]
You are right! I messed up with pulling `googletest` myself`.Thank you!

**Comment by bsamseth** [comment]
Good! Thanks again for giving me the heads up about the typo. The repo has not been updated in a little while, so this was a nice prompt to make sure it still works as advertised!
