### ISSUE TITLE
fatal error: doctest.h: No such file or directory  

### ISSUE THREAD

**Issue by ThomasP1988** [bsamseth/cpp-project#26]
Hi bsamseth,

First of all, thank you for this boilerplate which gives me a good idea on how to organise folder and cmake, however i have an issue when following your steps, when running the command: make i get this error

`[ 16%] Building CXX object CMakeFiles/test.dir/src/example.cpp.o
In file included from /home/tom/Projects/test/src/example.cpp:1:
/home/tom/Projects/test/include/example.h:22:10: fatal error: doctest.h: No such file or directory
   22 | #include "doctest.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test.dir/build.make:63: CMakeFiles/test.dir/src/example.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:452: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:95: all] Error 2`

Any idea what is happening here?

**Comment by ThomasP1988** [comment]
Ok, I fixed it, i had two problems:
In visual studio code, my vscode/cpp_properties.json didnt have the good cpp standard, and when i did add doctest manually, i didnt pay attention that it was included as doctest/doctest, now works like a charm :)

**Comment by bsamseth** [comment]
I'm glad you found this useful and that you sorted it out rather quickly! Don't hesitate to reach out again if you have issues and/suggestions.
