### ISSUE TITLE
CMake minimum version

### ISSUE THREAD

**Issue by EhssanD** [bsamseth/cpp-project#34]
I think the CMake minimum required version should be set to 3.12 because of using target_link_libraries with object libraries. 

I got the following on CMake v 3.10 :

```
CMake Error at CMakeLists.txt:58 (target_link_libraries):
  Object library target "engine" may not link to anything.
```
Which is gone by updating to the latest version. 

More on this:
https://gitlab.kitware.com/cmake/cmake/-/issues/18010
https://gitlab.kitware.com/cmake/cmake/-/issues/14778

**Comment by bsamseth** [comment]
Thanks for reporting this. Given that most new Linux distributions now ship a more recent version than 3.12 (and on MacOS and Windows I believe you need an explicit install anyway), I think upping the requirement should have minimal impact. I do find it curious that this hasn't come up earlier for me, I know for a fact I had <3.12 when this project started. But it probably got introduced in later revisions, at which point I must have had a newer CMake.

Anyways, thanks for reporting!
