### ISSUE TITLE
No rule to make target 'doc'

### ISSUE THREAD

**Issue by navono** [bsamseth/cpp-project#37]
Build with Debug mode in CLion, `make doc` failed with:
```
make: *** No rule to make target 'doc'.  Stop.
```

**Comment by navono** [comment]
After install `doxygen` and `graphviz` manual, it works. Dependencies may be placed in `setup.sh`?

**Comment by bsamseth** [comment]
Thanks for reporting this. I don't think the setup script should try to install any optional dependencies. Doing so in a consistent way across all platforms will be a real pain. The CMake build log should highlight that doxygen is not found and the user can choose to install it if wanted (just like you did). So my preference is to leave things like they are.
