### ISSUE TITLE
doctest - verbose information after `make test`

### ISSUE THREAD

**Issue by ljaniec** [bsamseth/cpp-project#39]
Hi,

Overall, I find this repository useful but I have to ask - how could I get verbose information after `make test` (failed and succeed cases)?  
Right now I use `./unit_tests` for more information or I go into `build/Testing/Temporary/LastTest.log` for detailed outputs. I would like to see it automatically after `make test` thought.

Best regards
Lukasz

**Comment by bsamseth** [comment]
Hi, @ljaniec ! The `make test` target is set up to use CMake's CTest system. You can get more verbose output on _failures_ by setting an environment variable when running it:

``` bash
CTEST_OUTPUT_ON_FAILURE=1 make test
```

Alternatively you can make a custom target and have that run the main test executable. For example, adding this to [tests/CMakeLists.txt](tests/CMakeLists.txt):

```cmake
add_custom_target(mytarget
    ${TEST_MAIN} -s
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
```

With this, running `make mytarget` gets you something like this:

```
make mytarget
[ 25%] Built target engine
[100%] Built target unit_tests
[doctest] doctest version is "2.3.6"
[doctest] run with "--help" for options
===============================================================================
/tmp/cpp-project/include/example.h:23:
TEST CASE:  we can have tests in headers if we want

/tmp/cpp-project/include/example.h:26: SUCCESS: CHECK( d.doSomething() == true ) is correct!
  values: CHECK( true == true )

===============================================================================
/tmp/cpp-project/src/example.cpp:17:
TEST CASE:  we can have tests written here, to test impl. details

/tmp/cpp-project/src/example.cpp:19: SUCCESS: CHECK( true ) is correct!
  values: CHECK( true )

===============================================================================
/tmp/cpp-project/tests/dummy.cpp:7:
TEST CASE:  complicated integration tests could be here

/tmp/cpp-project/tests/dummy.cpp:10: SUCCESS: CHECK( d.doSomething() == true ) is correct!
  values: CHECK( true == true )

===============================================================================
[doctest] test cases:      3 |      3 passed |      0 failed |      0 skipped
[doctest] assertions:      3 |      3 passed |      0 failed |
[doctest] Status: SUCCESS!
[100%] Built target mytarget
```

In this example I added `-s` as an argument to the test runner, which gives more output also for successful cases. You can run `./unit_tests --help` to see all the options. 

If you really want, you can also remove the parts relating to CTest and free up the name `test`, and make your custom target be named that instead.

Hopefully one of these options suits you well :)
