### ISSUE TITLE
Humble request for help

### ISSUE THREAD

**Issue by yishak-cs** [bsamseth/cpp-project#48]
Got assigned a project to make a program that handles passport applicants in the order the come for regulars and give priority to some special applicants and the program has to use a tree to store applicants info and later transfer it's content to priority queue that handles scheduling. Pls I need help

**Comment by bsamseth** [comment]
While I appreciate you are seeking some guidance, this is not the place for it. I'm certain you have more appropriate resources to ask for help, starting with the person or persons that assigned you the project. Best of luck.
