### ISSUE TITLE
Code Coverage fails in Mac OS

### ISSUE THREAD

**Issue by HenryRLee** [bsamseth/cpp-project#7]
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- Building with the following extra flags:  -Wall -Wextra
CMake Error at cmake/CodeCoverage.cmake:58 (MESSAGE):
  Compiler is not GNU gcc or Clang! Aborting...
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/lee/Studio/git/cpp-project/build/CMakeFiles/CMakeOutput.log".

**Comment by bsamseth** [comment]
Fixed by #8.
